[package]
name = "forestry"
version = "0.1.0"
authors = ["Jesse Stricker"]
edition = "2021"
description = "🌳 Keep your project directory trees in shape!"
homepage = "https://github.com/jessestricker/forestry"
repository = "https://github.com/jessestricker/forestry"
license = "MIT"
categories = ["command-line-utilities", "development-tools"]
publish = false

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.11", features = ["derive"] }
clap-verbosity-flag = "1.0.1"
env_logger = "0.9.0"
log = "0.4.17"
serde = { version = "1.0.140", features = ["derive"] }
toml = "0.5.9"
