name: Check

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions: {}

jobs:
  test:
    name: Test
    strategy:
      matrix:
        runner: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: dtolnay/rust-toolchain@0f2a41247f0cbad73dfdcf76a755e952ccdd5628 # master
        with: { toolchain: stable }
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0

      - run: cargo test --all-targets --locked --verbose

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: dtolnay/rust-toolchain@0f2a41247f0cbad73dfdcf76a755e952ccdd5628 # master
        with: { toolchain: stable, components: clippy }
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0

      - run: cargo install clippy-sarif sarif-fmt
      - run: >
          cargo clippy --all-targets --locked --message-format=json -- --deny warnings 
          | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - uses: github/codeql-action/upload-sarif@a59fbe22086cdbbb45d9e16c202e29c781bf2d5e # v2.1.22
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: dtolnay/rust-toolchain@0f2a41247f0cbad73dfdcf76a755e952ccdd5628 # master
        with: { toolchain: stable, components: rustfmt }
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0

      - run: cargo fmt --check --all --verbose -- --verbose
