name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and test the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test via Cargo
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --all-features

  lint:
    name: Run the Clippy linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - name: Install analysis dependencies
        run: cargo install clippy-sarif sarif-fmt

      - name: Run Clippy
        continue-on-error: true
        run: >
          cargo clippy
          --all-targets --all-features
          --message-format=json
          | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt

      - name: Upload analysis results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  format:
    name: Run the Rustfmt formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: Run Rustfmt via Cargo
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --all
